---
- hosts: deploy
 remote_user: root
 tasks:
   - name: install nginx
     apt:
       name: nginx
       state: latest

   - name: install curl
     apt:
       name: curl
       state: latest

   - name: update curl
     shell: curl -sL https://deb.nodesource.com/setup_8.x | sh

   - name: install nodejs and npm
     apt:
       name: nodejs
       state: latest

   - name: install git
     apt:
       name: git
       state: latest

   - name: clone nodejs project from git repository
     git:
       repo: https://git.mrzee.fr/student/my-node-project.git
       dest: /var/www/my-node-project

   - name: install nodejs dependencies
     npm:
       path: /var/www/my-node-project/myapp/

   - name: global install pm2
     npm:
        name: pm2
        global: yes

   - name: run myapp
     shell: pm2 start /var/www/my-node-project/myapp/bin/www

   - name: copy vhost to nginx sites-enabled
     shell: cp /var/www/my-node-project/vhost /etc/nginx/sites-enabled/default

   - name: restart nginx
     shell: service nginx restart